from tkinter import *

def tehtudvalik(var):
    f=var.get()
    if f:
        texbox.configure(show="")
        valik.configure(image=pilt1)
    else:
        texbox.configure(show="*")
        valik.configure(image=pilt2)
def textpealkirjasse():
    t=texbox.get()
    pealkiri.configure(text=t)
    texbox.delete(0,END)
aken=Tk()
aken.geometry("500x500")
aken.title("Autoriseerimine või registreerimine")
aken.configure(bg="#08ffa8")
aken.iconbitmap("ico.ico")
pealkiri=Label(aken,text="Autoriseerimine",bg="#08ffd2",fg="#13ad9e",cursor="star",font="Kunstler_Script 16", justify=CENTER, height=3, width=26)
raam=Frame(aken)
texbox=Entry(raam,bg="#08ffd2",fg="#13ad9e",cursor="star",font="Kunstler_Script 16",width=16,show="*")
pilt1=PhotoImage(file="3.png")
pilt2=PhotoImage(file="4.png")
var=BooleanVar() #IntVar(), StringVar()
valik=Checkbutton(raam,image=pilt2,variable=var,onvalue=True,offvalue=False,command=lambda:tehtudvalik(var))
#valik.deselect()
nupp=Button(raam,text="Sisenema",bg="#08ffd2",fg="#13ad9e",cursor="star",width=16,command=textpealkirjasse)
pealkiri2=Label(aken,text="Registreerimine",bg="#08ffd2",fg="#13ad9e",cursor="star",font="Kunstler_Script 16", justify=CENTER, height=3, width=26)
raam2=Frame(aken)
texbox=Entry(raam,bg="#08ffd2",fg="#13ad9e",cursor="star",font="Kunstler_Script 16",width=16,show="*")
pilt1=PhotoImage(file="3.png")
pilt2=PhotoImage(file="4.png")
var=BooleanVar() #IntVar(), StringVar()
valik=Checkbutton(raam,image=pilt2,variable=var,onvalue=True,offvalue=False,command=lambda:tehtudvalik(var))
#valik.deselect()
nupp=Button(raam,text="Sisenema",bg="#08ffd2",fg="#13ad9e",cursor="star",width=16,command=textpealkirjasse)

pealkiri.pack()
pealkiri2.pack()
raam.pack()
raam2.pack()
texbox.grid(row=0,column=0)
valik.grid(row=0,column=1)
nupp.grid(row=0,column=2)
aken.mainloop()
